
%---------------------------------------------------------------
% slidesPerello.sty by Miquel Perelló Nieto, 2013
%---------------------------------------------------------------

%-------------------------- identification ---------------------
%\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{Latex/Classes/slidesPerello}[2013/05/14 v1 slides beamer]

\LoadClass{beamer}

%\include{../Macros/figurePerello}
%\usepackage{../StyleFiles/slidesPerello}

%\renewcommand{\end{document}}{
%{
%\setbeamertemplate{logo}{}
%\begin{frame}
%  \titlepage
%\end{frame}
%}
%\end{document}
%}
%
